### ISSUE TITLE
I Like It 

### ISSUE THREAD

**Issue by louisw22** [BuiltBrokenModding/BasicIndustry#1]
Remember my curse messages about using other mods for recipies in ICBM??? Hopefully, this will be great! I recommend not sticking to close to Industrialcraft's style though because it is becoming outdated in the world of minecraft mods even though it is still used heavily.

**Comment by DarkGuardsman** [comment]
Idea it to make a bridge between the old style mods like IC2 and what i have planned for later. Baby steps in other words. It also makes a great mod to test the basic functions of our engine. Especially the power system which becomes hard to test on complex machines.
